### ISSUE TITLE
Provide container image for pegasus

### ISSUE THREAD

**Issue by liangyuanpeng** [apache/incubator-pegasus#1165]
## Feature Request

**Is your feature request related to a problem? Please describe:**

I had try to use github action to build pegasus and it in standalone action, considering that we already have a [nightly github action for build](https://github.com/apache/incubator-pegasus/blob/master/.github/workflows/regular-build.yml), it would be great if it could be include build and push docker image.

Unfortunately, it's running in a container, and I try to mount the host's docker command, which doesn't seem to work.

Some like that:

```yaml
     container:
       image: apache/pegasus:thirdparties-bin-${{ matrix.os }}-master
       volumes:
         - /var/run/docker.sock:/var/run/docker.sock 
         - /usr/bin/docker:/usr/bin/docker
``` 

Whether to consider using github action machine instead of container to build pegasus.

/cc @acelyc111 

**Describe the feature you'd like:**
Container image of pegasus.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

1. User must compile pegasus if they want to use pegasus, provide a container image of pegasus can run pegasus quick.
2. Use pegasus container instead of compile pegasus to run CI for client code. This can greatly improve efficiency.
