### ISSUE TITLE
Checking issue for github always failed

### ISSUE THREAD

**Issue by empiredan** [apache/incubator-pegasus#1551]
`neofinancial/ticket-check-action@v1.3.0` always failed as below: 

```
Run neofinancial/ticket-check-action@v1.3.0
  with:
    token: ***
    titleFormat: %title%
    quiet: true
    bodyRegex: #(\d+)
    bodyURLRegex: http(s?):\/\/(github.com)(\/apache)(\/incubator-pegasus)(\/issues)\/\d+
    ticketPrefix: #
    titleRegex: ^(CH)(-?)(\d{3,})
    titleRegexFlags: gi
    branchRegex: ^(CH)(-?)(\d{3,})
    branchRegexFlags: gi
    bodyRegexFlags: gim
    bodyURLRegexFlags: gim
/home/runner/work/_actions/neofinancial/ticket-check-action/v1.3.0/build/index.js:1
module.exports=function(e,t){"use strict";var r={};function __webpack_require__(t){if(r[t]){return r[t].exports}var i=r[t]={i:t,l:false,exports:{}};e[t].call(i.exports,i,i.exports,__webpack_require__);i.l=true;return i.exports}__webpack_require__.ab=__dirname+"/";function startup(){return __webpack_require__(3[2](https://github.com/apache/incubator-pegasus/actions/runs/5385704346/jobs/9774987825?pr=1548#step:2:2)5)}return startup()}({0:function(e,t,r){const{requestLog:i}=r(916);const{restEndpointMethods:n}=r(842);const s=r(529);const o=[r(190),r(19),i,r(148),n,r(4[3](https://github.com/apache/incubator-pegasus/actions/runs/5385704346/jobs/9774987825?pr=1548#step:2:3)0),r(850)];const a=s.plugin(o);function DeprecatedOctokit(e){const t=e&&e.log&&e.log.warn?e.log.warn:console.warn;t('[@octokit/rest] `const Octokit = require("@octokit/rest")` is deprecated. Use `const { Octokit } = require("@octokit/rest")` instead');return new a(e)}const u=Object.assign(DeprecatedOctokit,{Octokit:a});Object.keys(a).forEach(e=>{if(a.hasOwnProperty(e)){u[e]=a[e]}});e.exports=u},2:function(e,t,r){"use strict";const i=r(87);const n=r(118);const s=r([4](https://github.com/apache/incubator-pegasus/actions/runs/5385704346/jobs/9774987825?pr=1548#step:2:4)9);const o=(e,t)=>{if(!e&&t){throw new Error("You can't specify a `release` without specifying `platform`")}e=e||i.platform();let r;if(e==="darwin"){if(!t&&i.platform()==="darwin"){t=i.release()}const e=t?Number(t.split(".")[0])>1[5](https://github.com/apache/incubator-pegasus/actions/runs/5385704346/jobs/9774987825?pr=1548#step:2:5)?"macOS":"OS X":"macOS";r=t?n(t).name:"";return e+(r?" "+r:"")}if(e==="linux"){if(!t&&i.platform()==="linux"){t=i.release()}r=t?t.replace(/^(\d+\.\d+).*/,"$1"):"";return"Linux"+(r?" "+r:"")}if(e==="win32"){if(!t&&i.platform()==="win32"){t=i.release()}r=t?s(t):"";return"Windows"+(r?" "+r:"")}return e};e.exports=o},9:function(e,t,r){var i=r(9[6](https://github.com/apache/incubator-pegasus/actions/runs/5385704346/jobs/9774987825?pr=1548#step:2:6)9);var n=function(){};var s=function(e){return e.setHeader&&typeof e.abort==="function"};var o=function(e){return e.stdio&&Array.isArray(e.stdio)&&e.stdio.length===3};var a=function(e,t,r){if(typeof t==="function")return a(e,null,t);if(!t)t={};r=i(r||n);var u=e._writableState;var p=e._readableState;var c=t.readable||t.readable!==false&&e.readable;var d=t.writable||t.writable!==false&&e.writable;var l=false;var g=function(){if(!e.writable)m()};var m=function(){d=false;if(!c)r.call(e)};var h=function(){c=false;if(!d)r.call(e)};var y=function(t){r.call(e,t?new Error("exited with error code: "+t):null)};var f=function(t){r.call(e,t)};var b=function(){process.nextTick(_)};var _=function(){if(l)return;if(c&&!(p&&(p.ended&&!p.destroyed)))return r.call(e,new Error("premature close"));if(d&&!(u&&(u.ended&&!u.destroyed)))return r.call(e,new Error("premature close"))};var q=function(){e.req.on("finish",m)};if(s(e)){e.on("complete",m);e.on("abort",b);if(e.req)q();else e.on("request",q)}else if(d&&!u){e.on("end",g);e.on("close",g)}if(o(e))e.on("exit",y);e.on("end",h);e.on("finish",m);if(t.error!==false)e.on("error",f);e.on("close",b);return function()

...... (omit since it's too long)

```
